language: python
python:
  - 3.3
  - 3.4
matrix:
  fast_finish: true
sudo: false
install:
  - "pip install -qU --compile pip"
  - "pip install -qU --compile coverage flake8 sphinx_rtd_theme"
script:
  - "pip install -qU --compile ."
  - "python setup.py build_sphinx"
  - "flake8"
  - "nosetests"
