language: python
python:
  - 3.4
  - 3.5
matrix:
  fast_finish: true
sudo: false
install:
  - "pip install -qU --compile pip"
  - "pip install -qU --compile coverage pylint sphinx_rtd_theme"
script:
  - "pip install -qU --compile ."
  - "pylint -E torment test_torment"
  - "pylint torment test_torment; export STATUS=${?}; test ${STATUS} -gt 16 && exit ${STATUS} || exit 0"
  - "SPHINXOPTS='-n -W' make -eC docs html"
  - "nosetests"
